import {ASSIGNMENT_GRADING_ROUTE} from './coursePaths';
import {VOCABULARY_ROUTE_PATTERNS} from '@/pages/vocabulary/routes';

export const STUDENT_PLAN_VIEWS = {overview: 'overview', tasks: 'tasks', learning: 'learning', messages: 'messages'} as const;

export const STUDY_PLAN_QUERY_PARAMS = {checkpoint: 'checkpoint', task: 'task'} as const;

/** The same paths register the router and validate backend-provided navigation. */
export const APP_ROUTE_PATHS = {
  login: '/login',
  signup: '/signup',
  forgotpassword: '/forgotpassword',
  mockExamsStudentMockExamIdSection: '/mock-exams/:studentMockExamId/:section',
  home: '/',
  course: '/course',
  courseCourseId: '/course/:courseId',
  courseCourseIdOperations: '/course/:courseId/operations',
  courseCourseIdAssignmentsAssignmentId: '/course/:courseId/assignments/:assignmentId',
  courseCourseIdAssignmentsNew: '/course/:courseId/assignments/new',
  courseCourseIdAssignmentsAssignmentIdEdit: '/course/:courseId/assignments/:assignmentId/edit',
  courseCourseIdAssignmentsAssignmentIdSubmissionsSubmissionId: '/course/:courseId/assignments/:assignmentId/submissions/:submissionId',
  courseCourseIdAnnouncementsSubjectId: '/course/:courseId/announcements/:subjectId',
  courseCourseIdAnnouncements: '/course/:courseId/announcements',
  courseCourseIdEvents: '/course/:courseId/events',
  courseCourseIdEventsEventId: '/course/:courseId/events/:eventId',
  courseCourseIdSchedule: '/course/:courseId/schedule',
  courseCourseIdGroups: '/course/:courseId/groups',
  courseCourseIdGroupSetsGroupSetId: '/course/:courseId/group-sets/:groupSetId',
  courseCourseIdWeeksSubjectId: '/course/:courseId/weeks/:subjectId',
  courseCourseIdQuizzesNew: '/course/:courseId/quizzes/new',
  courseCourseIdQuizzesQuizId: '/course/:courseId/quizzes/:quizId',
  courseCourseIdQuizzesQuizIdEdit: '/course/:courseId/quizzes/:quizId/edit',
  courseCourseIdQuizzesQuizIdGrading: '/course/:courseId/quizzes/:quizId/grading',
  courseCourseIdGrades: '/course/:courseId/grades',
  courseAddContent: '/course/add-content',
  calendar: '/calendar',
  myOperations: '/my-operations',
  post: '/post',
  postPostId: '/post/:postId',
  roster: '/roster',
  rosterCourseId: '/roster/:courseId',
  profile: '/profile',
  createContentType: '/create/:contentType',
  aibot: '/aibot',
  settings: '/settings',
  admin: '/admin',
  adminDashboard: '/admin/dashboard',
  counsellor: '/counsellor',
  counsellorIntakes: '/counsellor/intakes',
  counsellorIntakesNew: '/counsellor/intakes/new',
  counsellorIntakesIntakeId: '/counsellor/intakes/:intakeId',
  counsellorIntakesIntakeIdAssign: '/counsellor/intakes/:intakeId/assign',
  advisorStudents: '/advisor/students',
  advisorOperations: '/advisor/operations',
  advisorTasks: '/advisor/tasks',
  advisorCourses: '/advisor/courses',
  advisorSchedule: '/advisor/schedule',
  advisorMessages: '/advisor/messages',
  advisorStudentsStudentUserId: '/advisor/students/:studentUserId',
  advisorStudentsStudentUserIdIntake: '/advisor/students/:studentUserId/intake',
  advisorStudentsStudentUserIdProfile: '/advisor/students/:studentUserId/profile',
  advisorStudentsStudentUserIdStudyPlan: '/advisor/students/:studentUserId/study-plan',
  advisorStudentsStudentUserIdCourses: '/advisor/students/:studentUserId/courses',
  advisorStudentsStudentUserIdSupport: '/advisor/students/:studentUserId/support',
  advisorStudentsStudentUserIdExams: '/advisor/students/:studentUserId/exams',
  myPlan: '/my-plan',
  parent: '/parent',
  mockExams: '/mock-exams',
  adminIntakes: '/admin/intakes',
  adminStudentsStudentUserId: '/admin/students/:studentUserId',
  advisorCoursesCourseIdDelivery: '/advisor/courses/:courseId/delivery',
} as const;

export const REGISTERED_ROUTE_PATTERNS = [...Object.values(APP_ROUTE_PATHS), ASSIGNMENT_GRADING_ROUTE, ...Object.values(VOCABULARY_ROUTE_PATTERNS)];

export const STUDENT_LEARNING_PATH = `${APP_ROUTE_PATHS.myPlan}?view=${STUDENT_PLAN_VIEWS.learning}`;
